apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-5k7hk73aq8oe8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-5k7hk73aq8oe8
    app.kubernetes.io/part-of: test-gitlabrenovate-p5ob2w3fcr944
  name: component-5k7hk73aq8oe8
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-5k7hk73aq8oe8
status:
  loadBalancer: {}
